name: Update C GLFW submodule

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Update submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --recursive --remote
