name: Update C GLFW submodule

on:
  schedule:
    - cron: '*/01 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update submodules & sync code
      run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         # updates GLFW submodule
         git submodule update --init --recursive
         git submodule update --recursive --remote
         # Sync v3.3 golang code to dev golang code
         find v3.3 -type f ! -wholename "*/glfw/glfw/*" -exec cp -v -t dev/glfw {} +
         # Commit changes
         git status
         git add .
         git commit -m "Automatic update of GLFW submodule" || echo "Nothing to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: ${{ github.repository }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
