name: Update C GLFW submodule

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --init --recursive
    - name: Update submodules
      uses: srt32/git-actions@v0.0.3
      with:
        args: git submodule update --recursive --remote
    - name: Commit changes
      run: |
         git config --local user.email "action@github.com"
         git config --local user.name "GitHub Action"
         git status
         git add .
         git commit -m "Automatic update of GLFW submodule" || echo "Nothing to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: pchampio/glfw
        github_token: ${{ secrets.GITHUB_TOKEN }}
